### PR TITLE
Finish version 0.2.0

### PR DESCRIPTION
**Pull request by JSorngard**
I think we have done all the API work that's needed for version 0.2.0. This PR merges it into main for eventual publication.

This is also a good place to discuss if we think there is anything left to do.

### CODE REVIEW

**Comment by DomiDre** [comment]
Quite nice work you did there. Thanks for keeping at it! I am just looking into it if we can get the test coverage a bit higher again, otherwise I think we would be good to go :+1:

**Comment by JSorngard** [comment]
I totally missed that you placed the data api tests in the data_api.rs file (which makes total sense) and placed the tests I made in the files of each rule!

Should I move the ones I made to data_api.rs?

**Comment by JSorngard** [comment]
Also, should we add a [Backtrace](https://doc.rust-lang.org/std/backtrace/struct.Backtrace.html)to the errors?

**Comment by DomiDre** [comment]
> Also, should we add a [Backtrace](https://doc.rust-lang.org/std/backtrace/struct.Backtrace.html) to the errors?
> 
> As in:
> ...

Backtrace sounds like a good thing to add for an error message :+1




> I completely missed that you placed the data api tests in the data_api.rs file (which makes total sense) and so I placed the tests I made in the files of each rule!
> 
> Should I move the ones I made to data_api.rs?

I was also thinking back and forth where to put them and I think both places might make sense. I put my first test into data_api, as I wanted to write some general tests that make sure that at least every element of the macros are somehow assessed anyhow in their basic functions (and chose Gauss Legendre then for its simplicity, but thought maybe also if one should test with a dummy/mock quadrature rule that explicitly calls the macro and test the resulting iterators etc., but was too tired to try that in the evening or think if that even makes sense :D). 
As the tests are more specific to the different quadrature rules, I think it also makes sense to keep them where you put them.

**Comment by JSorngard** [comment]
> thought maybe also if one should test with a dummy/mock quadrature rule that explicitly calls the macro and test the resulting iterators etc., but was too tired to try that in the evening or think if that even makes sense :D

That's a neat idea I think! The tests I made only test some aspects of it, so testing something like a very simple version with trivial dummy data to ensure the structure off all the functionality sounds nice.

**Comment by DomiDre** [comment]
I added some tests to check for the output on errors, you think its too much to test for or fine? At least that made the coverage lamp green again ;-)

**Comment by JSorngard** [comment]
I added backtraces to all error types, as well as a `backtrace` function to access it.  
Currently the enums that were the errors in Jacobi and Laguerre are a separate `QuadratureRuleErrorReason` type and a component of the new errors. It seems like a lot of types though :S   
I also merged in this new structure into the tests you made.

> I added some tests to check for the output on errors, you think its too much to test for or fine? At least that made the coverage lamp green again ;-)

Green is good :P Usually I would be skeptical of testing a display impl of an error, but the ones for Jacobi and Laguerre are constructed programmatically, so it makes sense to check that they result in correct sentences.

**Review by DomiDre — APPROVED** [review]
Personally, I am pretty satisfied with the changes. Quite a bunch. Good job!  :-)

**Pull request merged**
