### PR TITLE
Add `par_integrate` function to all quadrature rule structs

### PR DESCRIPTION
**Pull request by JSorngard**
This PR adds parallel versions of the normal `integrate` functions to all quadrature rule structs to complete #47.
They are hidden behind the `rayon` feature flag, and the feature requirement should get automatically documented on docs.rs.

I haven't actually checked when they are faster than the serial versions x)

If one wants to try out the documentation of the feature requirement tag in the documentation one can do

    RUSTDOCFLAGS="--cfg docsrs"; cargo +nightly doc --all-features

on Linux, and

    $env:RUSTDOCFLAGS="--cfg docsrs"
    cargo +nightly doc --all-features

on Windows (in PowerShell).   
The final result should look like this:

bild

### CODE REVIEW

**Comment by JSorngard** [comment]
It might be best to add this in 0.2.1 in order to get 0.2.0 out the door.

**Comment by JSorngard** [comment]
Yeah... I gotta add some tests :o

**Comment by JSorngard** [comment]
Tests done! :D

**Comment by JSorngard** [comment]
What are your thoughts on this @DomiDre?

**Review by DomiDre — APPROVED** [review]
Changes and test are looking good to me :+1: So I got nothing I could complain about :-) (I am also not expert enough in rayon to know if there would be any trick to maybe  avoid writing the same code within integrate and within par_integrate except for the iter vs par_iter line... but thats also not really an issue)

**Comment by DomiDre** [comment]
I also just checked out of curiosity the speed gain by extending the benches functions. So for the functions I copy pasted one observes that the gain for simple integrals is non existant due to the overhead. However in the benches one can see that for expensive integrands a speedup can happen e.g. for simpson deg 1000 with the expensive integrand. I suppose the calculation must be above microsecond range. A stronger speedup can be observed when using par_integrate as double integral on a integrate() function (this way a single computation takes long enough to compensate the overhead and on my specific example I had a 7x speedup).

So I guess it's good job and will be helpful for calculating more computationally intensive integrals :+1:

**Comment by DomiDre** [comment]
Codecov suddenly starts throwing errors:
```
warning - 2024-08-16 21:43:52,102 -- Response status code was 500. --- {"retry": 0}
warning - 2024-08-16 21:43:52,102 -- Request failed. Retrying --- {"retry": 0}
warning - 2024-08-16 21:43:52,730 -- Response status code was 500. --- {"retry": 1}
warning - 2024-08-16 21:43:52,730 -- Request failed. Retrying --- {"retry": 1}
warning - 2024-08-16 21:43:53,829 -- Response status code was 500. --- {"retry": 2}
warning - 2024-08-16 21:43:53,829 -- Request failed. Retrying --- {"retry": 2}
Traceback (most recent call last):
  File "codecov_cli/main.py", line 85, in <module>
  File "codecov_cli/main.py", line 81, in run
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1688, in invoke
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "click/decorators.py", line 33, in new_func
  File "codecov_cli/commands/commit.py", line 64, in create_commit
  File "codecov_cli/services/commit/__init__.py", line 28, in create_commit_logic
  File "codecov_cli/services/commit/__init__.py", line 65, in send_commit_data
  File "codecov_cli/helpers/request.py", line 82, in wrapper
Exception: Request failed after too many retries
[PYI-2757:ERROR] Failed to execute script 'main' due to unhandled exception!
Warning: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```

I turned off that it fails the pipeline for now but will check again if this is just a temporary issue with the server ( I spontaneously dont see how the code changes could have caused this )

**Comment by JSorngard** [comment]
Huh that is odd. I don't think it seems like an error on our end. I agree with waiting a bit and seeing if it's fixed.

**Comment by JSorngard** [comment]
Seems to be fixed now. I assume they had a problem with their servers, as you said.

**Comment by JSorngard** [comment]
Now I added a (tiny) note of your benchmark findings to the `rayon` feature description as well.

**Pull request merged**
