### PR TITLE
[Draft] Unify node and weights

### PR DESCRIPTION
**Pull request by DomiDre**
Not ready to merge yet. 

PR for the changes needed to resolve issue #29. Unify nodes and weights as pairs in every quadrature rule, make field private and implement iterators.

### CODE REVIEW

**Comment by JSorngard** [comment]
Woop!

I started experimenting with a way to ensure that we implement the same data access API on all quadrature structs by using a macro. It currenlty has the nodes and weights split, but the benefit is that it's easy to change, since I only need to modify one place :D (for data stuff, not integration and such).

I did that in the file data_api.rs in the branch `data_api_macro`. It's also not complete yet, but seems like a nice idea.

**Comment by DomiDre** [comment]
Ah nice :sunglasses:  

I think I am missing here now only the iterator stuff. I dont quite get yet what you meant in the issue would be the best way. Maybe if you have time at some point it's best if you plug that part in :sweat_smile:

**Comment by JSorngard** [comment]
I saw this just now. I attempted the same thing in #46, by doing stuff with macros. In some ways it's neat and in others it could be dumb x). If you think it makes sense to do it that way I'll merge the macros into here, otherwise I'll add the iterator the normal way.

**Comment by JSorngard** [comment]
I managed to implement the API with macros in #46. In some ways it's neat and in others it could be dumb (I'm mostly worried about maintainance). If you think it makes sense to do it that way I'll merge the macros into here, otherwise I'll add the iterator the normal way :P

**Comment by DomiDre** [comment]
Ah nice. Yes I like your way with macros better let's take that. Less redundant code. We can also just merge your PR then and drop this one or? I dont I have anything here that is not already covered by the macros

**Comment by JSorngard** [comment]
That also works :P 
Though before we merge it I think it would be nice if you took a look at the changes I did to the `new` functions to see if I broke anything that the tests haven't caught.

**Pull request closed without merging**
