### PR TITLE
Compute Gauss-Legendre node-weight pairs with algorithm by Ignace Bogaert

### PR DESCRIPTION
**Pull request by JSorngard**
This PR implements #14.

This algorithm has the advantage of being able to compute a node-weight pair in O(1) time, and being embarrassingly parallel when computing many node-weight pairs. This PR implements the algorithm serially.  
It has the notable disadvantage of needing to embed ~140 kB of data in the binary.

Article reference: https://doi.org/10.1137/140954969  
Reference implementation:  https://sourceforge.net/projects/fastgausslegendrequadrature/  
The code in this PR is a modification of the serial part of: https://github.com/JSorngard/fast_gauleg

### CODE REVIEW

**Comment by JSorngard** [comment]
The parallelism can be implemented with rayon behind a feature flag, but I believe that would be more efficient if the `GaussLegendre` struct were to store a single vector of node-weight pairs instead of two separate vectors, and if `nodes_and_weights` returned a `Vec<NodeWeightPair>`. That would be a breaking API change however, and might not be desirable.

I can see if I can implement `par_nodes_and_weights`, `par_init` and `par_integrate` with the current API.

**Comment by JSorngard** [comment]
Just realized that some benchmarking should probably be done to determine if this method is worse for `degree`s. I will do those benchmarks and then see if e.g. switching between the methods depending on `degree` makes sense.

**Comment by JSorngard** [comment]
I have done benchmarks of degrees from 3 to 100 and in them it is very clear that this new algorithm is faster, also for lower degrees. Since it scales better I haven't bothered testing it with much larger degrees than this.  
I have written in the average runtime of Bogaert's algorithm when it is not possible to see in the plots.

bench_compare

I believe this means that it's okay to switch the algorithm out completely, for all degrees.

**Review by DomiDre — APPROVED** [review]
Everything is looking good to me. Thanks a lot & Good work!

**Pull request merged**
