### PR TITLE
Change constructor name to `new`

### LINKED ISSUE #34: Rename `init` to `new`
Part of the API change for version 0.2.0, and related to #27.

- [ ] Rename all constructors
- [ ] Update all tests to use the new name
- [ ] Update the docs to refer to the new name

### PR DESCRIPTION
**Pull request by JSorngard**
Intended to close #34 when completed

### CODE REVIEW

**Comment by JSorngard** [comment]
I think I got all of the usages 👍

**Comment by DomiDre** [comment]
Found another one in a docstring. Should that change not be noted in the changelog?

**Comment by JSorngard** [comment]
Nice find! 
Yeah this should definitely be in the changelog I just realized that there may be merge conflicts if more than one PR tries to write to the same line. It's not a problem?

**Comment by DomiDre** [comment]
Mh maybe but those merge conflicts should be manageable hopefully :-D. So probably best to keep track of changes and add it again

**Comment by JSorngard** [comment]
I'll add it in :D

**Pull request merged**
